## 1

Ordinal Encoding : it is used when there is ranking based on the categorical features
Label Encoding L it is used to give numerical labelling of values in the data set ,by default it will take alphabetical orders

In [13]:
## lABEL ENCODING 

import pandas as pd

df = pd.DataFrame({"Name":['Gaurav','Hira','GKD','Hina']})

In [22]:
df

Name
0  Gaurav
1    Hira
2     GKD
3    Hina

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
labelenc = LabelEncoder()

In [25]:
labelenc.fit_transform(df['Name'])

array([1, 3, 0, 2])

In [28]:
## ORDINAL ENCODING
from sklearn.preprocessing import OrdinalEncoder
ordinalenc = OrdinalEncoder(categories=[['Gaurav','Hira','Hina','GKD']])

In [29]:
ordinalenc.fit_transform(df[['Name']])

array([[0.],
       [1.],
       [3.],
       [2.]])

## 2

Target Guided Ordinal Encoding (TGOE) is a technique used in machine learning for encoding categorical variables based on the target variable. The primary goal is to capture the relationship between the categorical variable and the target variable, which can be useful in improving the predictive power of a model.

Here's how Target Guided Ordinal Encoding typically works:

Calculate the Mean (or any other measure) of the Target Variable:

For each category in the categorical variable, calculate the mean (or another measure, such as median) of the target variable. This means that you calculate the average target variable value for each category.
Order the Categories:

Order the categories based on the calculated mean values. This ordering is used to assign ordinal values to the categories, with categories having higher mean values receiving higher ordinal values.
Assign Ordinal Values:

Assign ordinal values to the categories based on the order established in step 2. The category with the highest mean value gets the highest ordinal value, and so on.
Replace Categorical Values with Ordinal Values:

Replace the original categorical values in the dataset with the corresponding ordinal values assigned in step 3.

## 3

Covariance is a statistical measure that quantifies the degree to which two variables change together. In other words, it measures the joint variability of two random variables. Covariance can be used to understand whether an increase in one variable would result in an increase or decrease in another variable

If the covariance between two variables is positive, it indicates that when one variable increases, the other variable tends to increase as well. Conversely, if the covariance is negative, it suggests that when one variable increases, the other variable tends to decrease. A covariance of zero implies no linear relationship between the variables, but it doesn't necessarily mean there is no relationship at all

## 4 

In [30]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Sample dataset
data = {'Color': ['red', 'green', 'blue', 'red', 'blue'],
        'Size': ['small', 'medium', 'large', 'medium', 'small'],
        'Material': ['wood', 'metal', 'plastic', 'wood', 'metal']}

df = pd.DataFrame(data)

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply label encoding to each column
for column in df.columns:
    df[column+'_encoded'] = label_encoder.fit_transform(df[column])

# Display the original and encoded dataframe
print("Original DataFrame:")
print(df[['Color', 'Size', 'Material']])
print("\nEncoded DataFrame:")
print(df[['Color_encoded', 'Size_encoded', 'Material_encoded']])


Original DataFrame:
   Color    Size Material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic
3    red  medium     wood
4   blue   small    metal

Encoded DataFrame:
   Color_encoded  Size_encoded  Material_encoded
0              2             2                 2
1              1             1                 0
2              0             0                 1
3              2             1                 2
4              0             2                 0


## 5

In [31]:
import numpy as np

# Sample data
age = [25, 30, 35, 40, 45]
income = [50000, 60000, 75000, 90000, 80000]
education_level = [12, 14, 16, 18, 20]

# Create a numpy array for the dataset
data = np.array([age, income, education_level])

# Calculate the covariance matrix
covariance_matrix = np.cov(data)

# Display the covariance matrix
print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[6.250e+01 1.125e+05 2.500e+01]
 [1.125e+05 2.550e+08 4.500e+04]
 [2.500e+01 4.500e+04 1.000e+01]]


## 6

"Gender" (Male/Female) : One-hot encoding
"Education Level" (High School/Bachelor's/Master's/PhD) : Ordinal or one-hot encoding
"Employment Status" (Unemployed/Part-Time/Full-Time) : Ordinal encoding

## 7 

In [32]:
import numpy as np

# Sample data
temperature = [25, 28, 22, 20, 30]
humidity = [60, 70, 75, 55, 80]
weather_condition = ['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Rainy']
wind_direction = ['North', 'South', 'East', 'West', 'North']

# Create a numpy array for the continuous variables
continuous_data = np.array([temperature, humidity])

# Calculate the covariance matrix for continuous variables
covariance_matrix_continuous = np.cov(continuous_data)

# Display the covariance matrix for continuous variables
print("Covariance Matrix for Continuous Variables:")
print(covariance_matrix_continuous)

# Convert categorical variables to numerical values (e.g., using label encoding)
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
weather_condition_encoded = label_encoder.fit_transform(weather_condition)
wind_direction_encoded = label_encoder.fit_transform(wind_direction)

# Combine continuous and encoded categorical variables
all_variables = np.vstack([continuous_data, weather_condition_encoded, wind_direction_encoded])

# Calculate the covariance matrix for all variables
covariance_matrix_all = np.cov(all_variables)

# Display the covariance matrix for all variables
print("\nCovariance Matrix for All Variables:")
print(covariance_matrix_all)


Covariance Matrix for Continuous Variables:
[[ 17.   27.5]
 [ 27.5 107.5]]

Covariance Matrix for All Variables:
[[ 17.    27.5   -2.    -1.  ]
 [ 27.5  107.5   -5.75  -7.75]
 [ -2.    -5.75   0.7    0.15]
 [ -1.    -7.75   0.15   1.3 ]]
